[workspace]
channels = ["conda-forge", "bioconda"]
name = "data-sw-visual-studio-code-server"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
code-server = ">=4.105.1,<5"
